apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: bankapp-vpa
  namespace: bankapp-namespace
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankapp-deployment
  updatePolicy:
    updateMode: "Auto" # Options: "Off", "Initial", "Auto"